name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cracker2709/public_restful_go:latest
    
    
    - uses: docker/build-push-action@v1
    - name: Push to Docker Hub
      with:
        #username: ${{ secrets.DOCKER_USERNAME }}
        #password: ${{ secrets.DOCKER_PASSWORD }}
        repository: cracker2709/public_restful_go:latest
        tag_with_ref: true

      
